name: Build and deploy Dockerized Node.js app to Azure Web App - CryptoAppApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Build and push Docker image
      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build . -t cryptoappregistry.azurecr.io/cryptoappapi:latest
          docker login cryptoappregistry.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker push cryptoappregistry.azurecr.io/cryptoappapi:latest
      
      # Deploy Docker image to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CryptoAppApi'
          slot-name: 'Production'
          images: 'cryptoappregistry.azurecr.io/cryptoappapi:latest'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_24176FFABB16487E85A645A7C4DB28C5 }}
